# vimproc : 非同期処理
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# vimshell: シェル
[[plugins]]
repo = 'Shougo/vimshell.vim'

# vimfiler: ファイラー
[[plugins]]
repo = 'Shougo/vimfiler.vim'

# unite: UI統合
[[plugins]]
repo = 'Shougo/unite.vim'

# mru: 最近開いたファイル取得
[[plugins]]
repo = 'Shougo/neomru.vim'

